### ISSUE TITLE
i2c::I2c methods are unreliable in 'release' builds

### ISSUE THREAD

**Issue by LeonardMH** [thejpster/tm4c-hal#12]
## Environment
I am using a Texas Instruments TIVA-C LaunchPad (EK-TM4C123GXL). I have used the [cortex-m-quickstart](https://github.com/rust-embedded/cortex-m-quickstart) project to bootstrap.

**This is my entire main.rs:**
```rust
#![no_std]
#![no_main]

// you can put a breakpoint on `rust_begin_unwind` to catch panics
extern crate panic_halt;

use tm4c123x_hal::prelude::*;
use tm4c123x_hal::delay::Delay;
use cortex_m_rt::entry;

use tm4c123x_hal::i2c::I2c;

#[entry]
fn main() -> ! {
    let cpu_periph = cortex_m::Peripherals::take().unwrap();
    let dev_periph = tm4c123x::Peripherals::take().unwrap();

    // set up a delay controller based on systick
    let system_control = dev_periph.SYSCTL.constrain();
    let clocks = system_control.clock_setup.freeze();
    let mut delay = Delay::new(cpu_periph.SYST, &clocks);

    // Set up GPIOs that we're going to use
    let pf = dev_periph.GPIO_PORTF.split(&system_control.power_control);
    let mut red_led = pf.pf1.into_push_pull_output();
    let mut blu_led = pf.pf2.into_push_pull_output();
    let mut grn_led = pf.pf3.into_push_pull_output();

    // gpio banks needed for I2C
    let mut pa = dev_periph.GPIO_PORTA.split(&system_control.power_control);
    let mut pe = dev_periph.GPIO_PORTE.split(&system_control.power_control);

    // set up I2C1
    let scl1 = pa.pa6.into_af_push_pull(&mut pa.control);
    let sda1 = pa.pa7.into_af_open_drain(&mut pa.control);
    let mut i2c1 = I2c::i2c1(
        dev_periph.I2C1,
        (scl1, sda1),
        400.khz(),
        &clocks,
        &system_control.power_control,
    );

    // set up I2C2
    let scl2 = pe.pe4.into_af_push_pull(&mut pe.control);
    let sda2 = pe.pe5.into_af_open_drain(&mut pe.control);
    let mut i2c2 = I2c::i2c2(
        dev_periph.I2C2,
        (scl2, sda2),
        400.khz(),
        &clocks,
        &system_control.power_control,
    );

    loop {
        // do an i2c transaction forever
        match i2c2.write(0x3C, &[0, 0, 1, 2, 3]) {
            Ok(_) => { red_led.set_low(); }
            Err(_) => { red_led.set_high(); }
        };
    }
}
```
**This is my .cargo/config:**
```toml
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "arm-none-eabi-gdb-py -q -x openocd.gdb"

rustflags = [
  # LLD (shipped with the Rust toolchain) is used as the default linker
  "-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)
```

**This is the relevant section of my Cargo.toml:**
```toml
[dependencies]
embedded-hal = "0.2.1"
cortex-m = "0.5.7"
cortex-m-rt = "0.6.3"
cortex-m-semihosting = "0.3.1"
panic-halt = "0.2.0"
tm4c123x = "0.7.0"
tm4c123x-hal = "0.6.0"

# this lets you use `cargo fix`!
[[bin]]
name = <removed>
test = false
bench = false

[profile.release]
opt-level = "s"
codegen-units = 1
debug = true # symbols are nice and they don't increase the size on Flash
lto = true
```

## Problem
With the proper I2C lines instrumented, when I perform `cargo clean && cargo run --release` I see the following waveform for a single transaction (expect: `S + ADDR + 0, 0, 1, 2, 3 + P`):

![screen shot 2018-11-02 at 18 53 54](https://user-images.githubusercontent.com/1936248/47945561-c2595b80-ded0-11e8-9226-39f959bff72f.png)

It looks great, performance-wise, but it is missing the first byte! When I perform `cargo clean && cargo run` I see the following waveform for a single transaction:

![screen shot 2018-11-02 at 19 08 05](https://user-images.githubusercontent.com/1936248/47945809-bff80100-ded2-11e8-9a88-dfb1f58dcb00.png)

It is poor from a performance standpoint, but gets all of the bytes in there.

## Suggestions
I don't yet know for sure what is going on here. I'm relatively new to rust and llvm (this feels like maybe something llvm is doing). The I2C code in `tm4c123x_hal::i2c` appears to be correct based on comparison with other C-based Launchpad projects which I know are working.

The only lead I have right now will be to start looking at the I2C peripheral. I have seen issues in the past on this peripheral where checking the `busy` bit too soon after setting the `run` bit would result in the `busy` bit not being set by the time that I checked it. I've never been able to get an answer on how many cycles are actually required between setting the `run` bit and checking the `busy` bit, but right now I suspect that to be the issue.

I will be playing around with this some more this weekend and if I come across anything I will update, in the meantime if anyone has suggestions, they would be very much appreciated.
